name: ruby-core

on:
  pull_request:

  push:
    branches:
      - master

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  ruby_core:
    name: ${{matrix.target}} under a ruby-core setup
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        target: [Rubygems, Bundler]
    steps:
      - name: Set up latest ruby as baseruby to be able to compile ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.1
          bundler: none
      - name: Checkout latest Ruby stable branch, to see how our stable branch fits in there
        uses: actions/checkout@v3
        with:
          repository: ruby/ruby
          path: ruby/ruby
          ref: ruby_3_1
      - name: Install libraries
        run: |
          set -x
          sudo apt-get update -q || :
          sudo apt-get install --no-install-recommends -q -y build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm-dev bison autoconf ruby
      - name: Build Ruby
        run: |
          autoconf
          ./configure -C --disable-install-doc
          make -j2
        working-directory: ruby/ruby
      - uses: actions/checkout@v3
        with:
          path: rubygems/rubygems
      - name: Sync tools
        run: |
          ruby tool/sync_default_gems.rb rubygems
        working-directory: ruby/ruby
      - name: Test RubyGems
        run: make -j2 -s test-all TESTS="rubygems --no-retry"
        working-directory: ruby/ruby
        if: matrix.target == 'Rubygems'
      - name: Test Bundler
        run: |
          git add .
          make test-bundler-parallel
        working-directory: ruby/ruby
        if: matrix.target == 'Bundler'
