name: spell

on:
  pull_request:

  push:
    branches:
      - 3.5

permissions:
  contents: read

jobs:
  spell:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: codespell-project/actions-codespell@406322ec52dd7b488e48c1c4b82e2a8b3a1bf630 # v2.1
