name: truffleruby-bundler

on:
  pull_request:

  push:
    branches:
      - master
      - 3.4

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

defaults:
  run:
    shell: bash

jobs:
  truffleruby_bundler:
    name: Bundler (Truffleruby)
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
      - name: Setup ruby
        uses: ruby/setup-ruby@904f3fef85a9c80a3750cbe7d5159268fd5caa9f # v1.145.0
        with:
          ruby-version: truffleruby-22.3
          bundler: none
      - name: Prepare dependencies
        run: |
          bin/rake spec:parallel_deps
      - name: Run Test
        run: |
          bin/parallel_rspec --tag truffleruby_only --tag truffleruby
        working-directory: ./bundler
    timeout-minutes: 20
